version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: da-ecommerce-shop-postgres-17
    environment:
      POSTGRES_DB: da-ecommerce-shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - da-ecommerce-shop-backend-network

  redis:
    image: redis:8-alpine
    container_name: da-ecommerce-shop-redis-8
    command: redis-server --requirepass MyStrongPassword123!@78963
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - da-ecommerce-shop-backend-network

  redis_insight:
    image: redis/redisinsight:3.2.0
    container_name: da-ecommerce-shop-redis-insight-3.2.0
    restart: always
    user: root
    ports:
      - 5540:5540
    volumes:
      - redis_insight_volume_data:/data
    networks:
      - da-ecommerce-shop-backend-network

  dpage-pgadmin4:
    image: dpage/pgadmin4:9.13
    container_name: da-ecommerce-shop-pgadmin4-9.13
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: 1
    ports:
      - '5050:80'
    networks:
      - da-ecommerce-shop-backend-network
    depends_on:
      - postgres
    volumes:
      - pgadmin4_data:/var/lib/pgadmin

networks:
  da-ecommerce-shop-backend-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  redis_insight_volume_data:
  pgadmin4_data:
